on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{ matrix.otp }} / rebar3 ${{ matrix.rebar }}
    strategy:
      matrix:
        otp: ["24", "25", "26"]
        rebar: ["3.19.0", "3.22.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{ matrix.rebar }}

      - name: Run tests
        run: ./rebar3 do eunit, ct
